# -*- coding: mbcs -*-
from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from connectorBehavior import *
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=200.0)
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(-25.0, 25.0), 
    point2=(25.0, -25.0))
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='Part-1', type=
    DEFORMABLE_BODY)
mdb.models['Model-1'].parts['Part-1'].BaseSolidExtrude(depth=20.0, sketch=
    mdb.models['Model-1'].sketches['__profile__'])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].parts['Part-1'].DatumPlaneByOffset(flip=SIDE1, offset=5.0
    , plane=mdb.models['Model-1'].parts['Part-1'].faces[4])
mdb.models['Model-1'].parts['Part-1'].DatumPlaneByOffset(flip=SIDE1, offset=
    10.0, plane=mdb.models['Model-1'].parts['Part-1'].faces[4])
mdb.models['Model-1'].parts['Part-1'].DatumPlaneByOffset(flip=SIDE1, offset=
    15.0, plane=mdb.models['Model-1'].parts['Part-1'].faces[4])
mdb.models['Model-1'].ConstrainedSketch(gridSpacing=4.26, name='__profile__', 
    sheetSize=170.58, transform=
    mdb.models['Model-1'].parts['Part-1'].MakeSketchTransform(
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['Model-1'].parts['Part-1'].edges[0], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 25.0)))
mdb.models['Model-1'].parts['Part-1'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['Model-1'].sketches['__profile__'])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-25.56, 25.56), 
    point2=(-25.56, -25.56))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[2])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-25.56, -25.56), 
    point2=(25.56, -25.56))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[2], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(25.56, -25.56), 
    point2=(25.56, 25.56))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[4])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[4])
mdb.models['Model-1'].sketches['__profile__'].Spline(points=((-25.56, 25.56), (
    -18.105, 29.82), (-11.715, 23.43), (-6.39, 26.625), (1.065, 23.43), (8.52, 
    26.625), (13.845, 23.43), (19.17, 26.625), (23.43, 23.43), (25.56, 25.56)))
mdb.models['Model-1'].parts['Part-1'].Wire(sketch=
    mdb.models['Model-1'].sketches['__profile__'], sketchOrientation=RIGHT, 
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[2], 
    sketchPlaneSide=SIDE1, sketchUpEdge=
    mdb.models['Model-1'].parts['Part-1'].edges[0])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].ConstrainedSketch(gridSpacing=4.64, name='__profile__', 
    sheetSize=185.96, transform=
    mdb.models['Model-1'].parts['Part-1'].MakeSketchTransform(
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[3], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['Model-1'].parts['Part-1'].edges[4], 
    sketchOrientation=RIGHT, origin=(0.0, 4.102123, 30.0)))
mdb.models['Model-1'].parts['Part-1'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['Model-1'].sketches['__profile__'])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-27.84, 23.2), 
    point2=(-27.84, -32.48))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[2])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-27.84, -32.48), 
    point2=(27.84, -32.48))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[2], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(27.84, -32.48), 
    point2=(27.84, 23.2))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[4])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[4])
mdb.models['Model-1'].sketches['__profile__'].Spline(points=((-27.84, 23.2), (
    -24.36, 25.52), (-20.88, 22.04), (-18.56, 23.2), (-12.76, 25.52), (-11.6, 
    23.2), (-9.28, 22.04), (-4.64, 22.04), (-2.32, 23.2), (4.64, 20.88), (6.96, 
    23.2), (10.44, 23.2), (12.76, 22.04), (15.08, 18.56), (18.56, 20.88), (
    22.04, 23.2), (23.2, 20.88), (27.84, 23.2)))
mdb.models['Model-1'].parts['Part-1'].Wire(sketch=
    mdb.models['Model-1'].sketches['__profile__'], sketchOrientation=RIGHT, 
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[3], 
    sketchPlaneSide=SIDE1, sketchUpEdge=
    mdb.models['Model-1'].parts['Part-1'].edges[4])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].ConstrainedSketch(gridSpacing=4.91, name='__profile__', 
    sheetSize=196.45, transform=
    mdb.models['Model-1'].parts['Part-1'].MakeSketchTransform(
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[4], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['Model-1'].parts['Part-1'].edges[8], 
    sketchOrientation=RIGHT, origin=(0.0, 2.693184, 35.0)))
mdb.models['Model-1'].parts['Part-1'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['Model-1'].sketches['__profile__'])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-29.46, 24.55), 
    point2=(-29.46, -29.46))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[2])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-29.46, -29.46), 
    point2=(29.46, -29.46))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[2], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3])
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], ))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[2], ))
mdb.models['Model-1'].sketches['__profile__'].ConstructionLine(point1=(-24.55, 
    19.64), point2=(-24.55, -24.55))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[4])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].ConstrainedSketch(gridSpacing=4.91, name='__profile__', 
    sheetSize=196.45, transform=
    mdb.models['Model-1'].parts['Part-1'].MakeSketchTransform(
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[4], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['Model-1'].parts['Part-1'].edges[8], 
    sketchOrientation=RIGHT, origin=(0.0, 2.693184, 35.0)))
mdb.models['Model-1'].parts['Part-1'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['Model-1'].sketches['__profile__'])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-24.55, 24.55), 
    point2=(-24.55, -24.55))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[2])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-24.55, -24.55), 
    point2=(24.55, -24.55))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[2], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(24.55, -24.55), 
    point2=(24.55, 24.55))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[4])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[4])
mdb.models['Model-1'].sketches['__profile__'].Spline(points=((-24.55, 24.55), (
    -20.8675, 25.7775), (-17.185, 23.3225), (-13.5025, 25.7775), (-8.5925, 
    25.7775), (-6.1375, 23.3225), (-2.455, 27.005), (-1.2275, 22.095), (3.6825, 
    25.7775), (7.365, 22.095), (12.275, 27.005), (17.185, 23.3225), (22.095, 
    23.3225), (24.55, 24.55)))
mdb.models['Model-1'].parts['Part-1'].Wire(sketch=
    mdb.models['Model-1'].sketches['__profile__'], sketchOrientation=RIGHT, 
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[4], 
    sketchPlaneSide=SIDE1, sketchUpEdge=
    mdb.models['Model-1'].parts['Part-1'].edges[8])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].parts['Part-1'].SolidLoft(endCondition=NONE, 
    loftsections=((mdb.models['Model-1'].parts['Part-1'].edges[12], 
    mdb.models['Model-1'].parts['Part-1'].edges[16], 
    mdb.models['Model-1'].parts['Part-1'].edges[19], 
    mdb.models['Model-1'].parts['Part-1'].edges[22]), (
    mdb.models['Model-1'].parts['Part-1'].edges[4], 
    mdb.models['Model-1'].parts['Part-1'].edges[5], 
    mdb.models['Model-1'].parts['Part-1'].edges[6], 
    mdb.models['Model-1'].parts['Part-1'].edges[7]), (
    mdb.models['Model-1'].parts['Part-1'].edges[0], 
    mdb.models['Model-1'].parts['Part-1'].edges[1], 
    mdb.models['Model-1'].parts['Part-1'].edges[2], 
    mdb.models['Model-1'].parts['Part-1'].edges[3]), (
    mdb.models['Model-1'].parts['Part-1'].edges[8], 
    mdb.models['Model-1'].parts['Part-1'].edges[9], 
    mdb.models['Model-1'].parts['Part-1'].edges[10], 
    mdb.models['Model-1'].parts['Part-1'].edges[11])), startCondition=NONE)
# Save by ptangnun on 2019_11_18-22.37.02; build 2017 2016_09_27-23.54.59 126836
