# -*- coding: mbcs -*-
from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from connectorBehavior import *
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=200.0)
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(-20.0, 15.0), 
    point2=(20.0, -20.0))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[5], ))
mdb.models['Model-1'].sketches['__profile__'].Spline(points=((-20.0, 15.0), (
    -15.0, 17.5), (-8.75, 13.75), (-2.5, 16.25), (5.0, 18.75), (7.5, 15.0), (
    10.0, 13.75), (15.0, 16.25), (16.25, 13.75), (20.0, 15.0)))
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='Part-1', type=
    DEFORMABLE_BODY)
mdb.models['Model-1'].parts['Part-1'].BaseWire(sketch=
    mdb.models['Model-1'].sketches['__profile__'])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].parts['Part-1'].DatumPlaneByPrincipalPlane(offset=10.0, 
    principalPlane=XYPLANE)
mdb.models['Model-1'].ConstrainedSketch(gridSpacing=3.19, name='__profile__', 
    sheetSize=127.78, transform=
    mdb.models['Model-1'].parts['Part-1'].MakeSketchTransform(
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['Model-1'].parts['Part-1'].edges[1], 
    sketchOrientation=RIGHT, origin=(0.0, 0.560276, 10.0)))
mdb.models['Model-1'].parts['Part-1'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['Model-1'].sketches['__profile__'])
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(-19.14, 19.14), 
    point2=(19.9375, -15.95))
mdb.models['Model-1'].sketches['__profile__'].ObliqueDimension(textPoint=(
    -8.21418380737305, -18.6878127736816), value=40.0, vertex1=
    mdb.models['Model-1'].sketches['__profile__'].vertices[3], vertex2=
    mdb.models['Model-1'].sketches['__profile__'].vertices[0])
mdb.models['Model-1'].sketches['__profile__'].ObliqueDimension(textPoint=(
    25.9062805175781, 1.10672286322021), value=35.09, vertex1=
    mdb.models['Model-1'].sketches['__profile__'].vertices[2], vertex2=
    mdb.models['Model-1'].sketches['__profile__'].vertices[3])
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].dimensions[1], ))
mdb.models['Model-1'].sketches['__profile__'].ObliqueDimension(textPoint=(
    25.9062805175781, -4.45851418206787), value=40.0, vertex1=
    mdb.models['Model-1'].sketches['__profile__'].vertices[2], vertex2=
    mdb.models['Model-1'].sketches['__profile__'].vertices[3])
mdb.models['Model-1'].sketches['__profile__'].ConstructionLine(point1=(-31.9, 
    0.0), point2=(38.28, 0.0))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[6])
mdb.models['Model-1'].sketches['__profile__'].DistanceDimension(entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[6], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], textPoint=(
    -27.2443733215332, -8.14636799523926), value=20.0)
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[5], 
    mdb.models['Model-1'].sketches['__profile__'].geometry[2], 
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], 
    mdb.models['Model-1'].sketches['__profile__'].geometry[2], 
    mdb.models['Model-1'].sketches['__profile__'].geometry[6], 
    mdb.models['Model-1'].sketches['__profile__'].geometry[6], 
    mdb.models['Model-1'].sketches['__profile__'].dimensions[0]))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[4], ))
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(-19.9375, 
    14.355), point2=(19.9375, -20.735))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[10], ))
mdb.models['Model-1'].sketches['__profile__'].Spline(points=((-19.9375, 
    14.355), (-16.7475, 13.5575), (-13.5575, 14.355), (-11.165, 15.95), (
    -5.5825, 15.95), (-2.3925, 17.545), (0.7975, 16.7475), (3.9875, 16.7475), (
    9.57, 14.355), (11.9625, 15.1525), (15.1525, 13.5575), (17.545, 15.1525), (
    19.9375, 14.355)))
mdb.models['Model-1'].parts['Part-1'].Wire(sketch=
    mdb.models['Model-1'].sketches['__profile__'], sketchOrientation=RIGHT, 
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[2], 
    sketchPlaneSide=SIDE1, sketchUpEdge=
    mdb.models['Model-1'].parts['Part-1'].edges[1])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].parts['Part-1'].SolidLoft(endCondition=NONE, 
    loftsections=((mdb.models['Model-1'].parts['Part-1'].edges[4], 
    mdb.models['Model-1'].parts['Part-1'].edges[5], 
    mdb.models['Model-1'].parts['Part-1'].edges[6], 
    mdb.models['Model-1'].parts['Part-1'].edges[7]), (
    mdb.models['Model-1'].parts['Part-1'].edges[0], 
    mdb.models['Model-1'].parts['Part-1'].edges[1], 
    mdb.models['Model-1'].parts['Part-1'].edges[2], 
    mdb.models['Model-1'].parts['Part-1'].edges[3])), startCondition=NONE)
del mdb.models['Model-1'].parts['Part-1'].features['Solid Loft-1']
mdb.models['Model-1'].parts['Part-1'].DatumPlaneByPrincipalPlane(offset=20.0, 
    principalPlane=XYPLANE)
mdb.models['Model-1'].ConstrainedSketch(gridSpacing=3.31, name='__profile__', 
    sheetSize=132.65, transform=
    mdb.models['Model-1'].parts['Part-1'].MakeSketchTransform(
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[5], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['Model-1'].parts['Part-1'].edges[5], 
    sketchOrientation=RIGHT, origin=(0.0, 0.472914, 20.0)))
mdb.models['Model-1'].parts['Part-1'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['Model-1'].sketches['__profile__'])
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(-19.86, 
    14.0675), point2=(19.86, -20.6875))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[5], ))
mdb.models['Model-1'].sketches['__profile__'].Spline(points=((-19.86, 14.0675), 
    (-16.55, 15.7225), (-14.0675, 14.0675), (-11.585, 14.0675), (-9.93, 
    14.895), (-5.7925, 15.7225), (-3.31, 13.24), (0.0, 14.895), (3.31, 
    15.7225), (4.965, 16.55), (8.275, 16.55), (11.585, 14.895), (13.24, 
    14.0675), (14.895, 15.7225), (18.205, 15.7225), (19.86, 14.0675)))
mdb.models['Model-1'].parts['Part-1'].Wire(sketch=
    mdb.models['Model-1'].sketches['__profile__'], sketchOrientation=RIGHT, 
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[5], 
    sketchPlaneSide=SIDE1, sketchUpEdge=
    mdb.models['Model-1'].parts['Part-1'].edges[5])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].parts['Part-1'].DatumPlaneByPrincipalPlane(offset=30.0, 
    principalPlane=XYPLANE)
mdb.models['Model-1'].ConstrainedSketch(gridSpacing=3.5, name='__profile__', 
    sheetSize=140.04, transform=
    mdb.models['Model-1'].parts['Part-1'].MakeSketchTransform(
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[7], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['Model-1'].parts['Part-1'].edges[9], 
    sketchOrientation=RIGHT, origin=(0.0, 0.452983, 30.0)))
mdb.models['Model-1'].parts['Part-1'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['Model-1'].sketches['__profile__'])
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(-20.125, 14.0), 
    point2=(20.125, -21.0))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[5], ))
mdb.models['Model-1'].sketches['__profile__'].Spline(points=((-20.125, 14.0), (
    -16.625, 13.125), (-12.25, 13.125), (-7.875, 14.875), (-6.125, 13.125), (
    -1.75, 14.875), (0.875, 13.125), (5.25, 12.25), (6.125, 14.875), (8.75, 
    14.0), (11.375, 12.25), (14.875, 13.125), (17.5, 14.875), (20.125, 14.0)))
mdb.models['Model-1'].parts['Part-1'].Wire(sketch=
    mdb.models['Model-1'].sketches['__profile__'], sketchOrientation=RIGHT, 
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[7], 
    sketchPlaneSide=SIDE1, sketchUpEdge=
    mdb.models['Model-1'].parts['Part-1'].edges[9])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].parts['Part-1'].DatumPlaneByPrincipalPlane(offset=40.0, 
    principalPlane=XYPLANE)
mdb.models['Model-1'].ConstrainedSketch(gridSpacing=3.76, name='__profile__', 
    sheetSize=150.48, transform=
    mdb.models['Model-1'].parts['Part-1'].MakeSketchTransform(
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[9], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['Model-1'].parts['Part-1'].edges[13], 
    sketchOrientation=RIGHT, origin=(0.0, 0.286767, 40.0)))
mdb.models['Model-1'].parts['Part-1'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['Model-1'].sketches['__profile__'])
mdb.models['Model-1'].sketches['__profile__'].rectangle(point1=(-19.74, -20.68)
    , point2=(19.74, 15.04))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], ))
mdb.models['Model-1'].sketches['__profile__'].Spline(points=((-19.74, 15.04), (
    -17.86, 16.92), (-15.04, 14.1), (-12.22, 15.98), (-9.4, 14.1), (-4.7, 
    14.1), (-3.76, 15.98), (0.0, 15.98), (1.88, 14.1), (5.64, 15.98), (8.46, 
    14.1), (10.34, 15.04), (13.16, 14.1), (15.98, 15.98), (19.74, 15.04)))
mdb.models['Model-1'].parts['Part-1'].Wire(sketch=
    mdb.models['Model-1'].sketches['__profile__'], sketchOrientation=RIGHT, 
    sketchPlane=mdb.models['Model-1'].parts['Part-1'].datums[9], 
    sketchPlaneSide=SIDE1, sketchUpEdge=
    mdb.models['Model-1'].parts['Part-1'].edges[13])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].parts['Part-1'].SolidLoft(endCondition=NONE, 
    loftsections=((mdb.models['Model-1'].parts['Part-1'].edges[8], 
    mdb.models['Model-1'].parts['Part-1'].edges[9], 
    mdb.models['Model-1'].parts['Part-1'].edges[10], 
    mdb.models['Model-1'].parts['Part-1'].edges[11]), (
    mdb.models['Model-1'].parts['Part-1'].edges[4], 
    mdb.models['Model-1'].parts['Part-1'].edges[5], 
    mdb.models['Model-1'].parts['Part-1'].edges[6], 
    mdb.models['Model-1'].parts['Part-1'].edges[7]), (
    mdb.models['Model-1'].parts['Part-1'].edges[12], 
    mdb.models['Model-1'].parts['Part-1'].edges[13], 
    mdb.models['Model-1'].parts['Part-1'].edges[14], 
    mdb.models['Model-1'].parts['Part-1'].edges[15]), (
    mdb.models['Model-1'].parts['Part-1'].edges[0], 
    mdb.models['Model-1'].parts['Part-1'].edges[1], 
    mdb.models['Model-1'].parts['Part-1'].edges[2], 
    mdb.models['Model-1'].parts['Part-1'].edges[3]), (
    mdb.models['Model-1'].parts['Part-1'].edges[16], 
    mdb.models['Model-1'].parts['Part-1'].edges[17], 
    mdb.models['Model-1'].parts['Part-1'].edges[18], 
    mdb.models['Model-1'].parts['Part-1'].edges[19])), startCondition=NONE)
# Save by ptangnun on 2019_12_01-18.11.53; build 2017 2016_09_27-23.54.59 126836
